---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "workadventure.fullname" . }}-secret-env-back
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: "{{ .Values.secretKey | b64enc }}"

  {{- range $key, $val := .Values.commonSecretEnv }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}

  {{- range $key, $val := .Values.back.secretEnv }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
