---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "workadventure.fullname" . }}-secret-env-ejabberd
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: "{{ .Values.ejabberdJwtSecret | b64enc }}"

  {{- range $key, $val := .Values.commonSecretEnv }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}

  {{- range $key, $val := .Values.ejabberd.secretEnv }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
