apiVersion: v1
kind: Service
metadata:
  name: {{ include "workadventure.fullname" . }}-mapstorage
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
    role: mapstorage
spec:
  type: {{ .Values.mapstorage.service.type }}
  ports:
    - port: {{ .Values.mapstorage.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 50053
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "workadventure.selectorLabels" . | nindent 4 }}
    role: mapstorage
