---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "workadventure.fullname" . }}-env-play
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
data:
  API_URL: {{ range $replica, $f := until (int .Values.back.replicaCount) }}{{ include "workadventure.fullname" $ }}-back-{{ $replica }}:50051{{ if ne $replica (sub (int $.Values.back.replicaCount) 1)  }}{{ "," }}{{ end }}{{ end }}
  CHAT_URL: /chat/
  ICON_URL: /icon
  UPLOADER_URL: /uploader
  PUSHER_URL: /
  FRONT_URL: /
  PUBLIC_MAP_STORAGE_URL: https://{{ .Values.domainName }}/map-storage
  EJABBERD_API_URI: {{ include "workadventure.fullname" . }}-back:{{ .Values.ejabberd.service.port }}
  ENABLE_OPENAPI_ENDPOINT: "true"
  ROOM_API_PORT: "50051"
  MAP_STORAGE_PATH_PREFIX: /map-storage
  EJABBERD_DOMAIN: {{ .Values.ejabberdDomain }}


  {{- range $key, $val := .Values.commonEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

  {{- range $key, $val := .Values.play.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
