apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workadventure.fullname" . }}-back
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
    role: back
spec:
  {{- if not .Values.back.autoscaling.enabled }}
  replicas: {{ .Values.back.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "workadventure.selectorLabels" . | nindent 6 }}
      role: back
  template:
    metadata:
      {{- with .Values.back.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "workadventure.selectorLabels" . | nindent 8 }}
        role: back
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "workadventure.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.back.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-back
          securityContext:
            {{- toYaml .Values.back.securityContext | nindent 12 }}
          image: "{{ .Values.back.image.repository }}:{{ .Values.back.image.tag | default .Values.appVersion }}"
          imagePullPolicy: {{ .Values.back.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "workadventure.fullname" . }}-env-back
            - secretRef:
                name: {{ include "workadventure.fullname" . }}-secret-env-back
          ports:
            - name: http
              containerPort: {{ .Values.back.service.port }}
              protocol: TCP
            - name: grpc
              containerPort: 50051
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.back.resources | nindent 12 }}
      {{- with .Values.back.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.back.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.back.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
