apiVersion: v1
kind: Service
metadata:
  name: {{ include "workadventure.fullname" . }}-chat
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
    role: chat
spec:
  type: {{ .Values.chat.service.type }}
  ports:
    - port: {{ .Values.chat.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "workadventure.selectorLabels" . | nindent 4 }}
    role: chat
