{{- if .Values.ingress.enabled -}}
{{- $fullName := include "workadventure.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-mapstorage-path
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotationsMapstoragePath }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.domainName }}
      secretName: {{ .Values.ingress.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /map-storage{{ .Values.ingress.rewritePathSuffix }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "workadventure.fullname" . }}-mapstorage
                port:
                  number: {{ .Values.mapstorage.service.port }}
{{- end }}
