---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "workadventure.fullname" . }}-env-uploader
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
type: Opaque
data:
  UPLOADER_URL: https://{{ .Values.domainName }}/uploader

  {{- range $key, $val := .Values.commonEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

  {{- range $key, $val := .Values.uploader.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
