---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "workadventure.fullname" . }}-secret-env-uploader
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.commonSecretEnv }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}

  {{- range $key, $val := .Values.uploader.secretEnv }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
